In [4]:
import os, sys
import torch

In [5]:
sys.path.append("/ssd/users/wergillius/Project/MTtrans/models")

In [6]:
from importlib import reload
import Modules

In [25]:
reload(Modules)

<module 'Modules' from '/ssd/users/wergillius/Project/MTtrans/models/Modules/__init__.py'>

In [7]:
Modules.RL_Atten

Modules.GP_net.RL_Atten

In [26]:
Modules.Atten_GP

Modules.GP_net.Atten_GP

In [11]:
from Modules import Backbone
from Modules import GP_net
from Modules import Koo_net
from Modules import zoo

In [3]:
torch.randn((32, 120, 93)).amax(dim=-1).shape

torch.Size([32, 120])

## hyper

In [67]:
# hyper parameter set for 100bp sequences
channel_ls = [4, 120, 120]
kernel_sizes = [8, 5]
strides = [1, 1]
pool_size = [10, 5]

arct_params = [channel_ls, kernel_sizes, strides, pool_size]
test_X = torch.randn((32,4, 100))

In [75]:
reload(Koo_net)

<module 'Modules.Koo_net' from '/ssd/users/wergillius/Project/MTtrans/models/Modules/Koo_net.py'>

In [76]:
network = Koo_net.Conf_CNN(*arct_params)

In [77]:
network(test_X).shape

torch.Size([32, 1])

In [59]:
network.network.Conv_1

Sequential(
  (0): Conv1d(4, 120, kernel_size=(8,), stride=(1,))
  (1): BatchNorm1d(120, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (2): Mish()
)

In [61]:
layer1_out =network.network.Conv_1(test_X)

layer1_out.shape

torch.Size([32, 120, 93])

In [62]:
max_pool1_out = network.network.MaxPool_1(layer1_out)
max_pool1_out.shape

torch.Size([32, 120, 9])

In [63]:
TestInput_l2 = torch.randn((32, 120, 9))
layer2_out = network.network.Conv_2(TestInput_l2)
layer2_out.shape

torch.Size([32, 120, 5])

In [64]:
max_pool2_out = network.network.MaxPool_2(layer2_out)
max_pool2_out.shape

torch.Size([32, 120, 1])

In [79]:
from torch import nn

In [80]:
test_linear = nn.Linear(4, 10)

In [82]:
test_linear(torch.randn(32, 12, 4)).shape

torch.Size([32, 12, 10])

In [8]:
768*64

49152

In [9]:
768/128

6.0

In [10]:
test_out = torch.randn((32,53, 128))

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51])

In [14]:
torch.arange(1, 53, 3)

tensor([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52])

In [15]:
torch.arange(2, 53, 3)

tensor([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

In [21]:
import numpy as np

In [30]:
test_out = []
for i in range(3):
    line = np.array([1,2,3]*18) + i *10
    test_out.append(line.tolist())

test_out_ay = np.asarray(test_out)

In [33]:
test_out_ay[:, np.arange(0, 54, 3)]

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1],
       [11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
        11, 11],
       [21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
        21, 21]])

In [34]:
test_out_ay[:, np.arange(1, 54, 3)]

array([[ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
         2,  2],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
        12, 12],
       [22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
        22, 22]])

In [35]:
test_out = torch.from_numpy(test_out_ay)

In [46]:
test_out_ts = torch.cat([test_out.view(1,54,3)]*4)

In [47]:
test_out_ts.shape

torch.Size([4, 54, 3])

In [66]:
manual_test = torch.tensor(
    [[[1,  2,  3,  4,  5,  6,  7,  8, 9],
     [11, 12, 13, 14, 15, 16, 17, 18, 19],
     [21, 22, 23, 24, 25, 26, 27, 28, 29]
    ],
    [[1,  2,  3,  4,  5,  6,  7,  8, 9],
     [11, 12, 13, 14, 15, 16, 17, 18, 19],
     [21, 22, 23, 24, 25, 26, 27, 28, 29]
    ]]
).transpose(1,2)
manual_test -= 1

In [68]:
manual_test.shape

torch.Size([2, 9, 3])

In [95]:
manual_test.select(1, torch.tensor([0,3]))

TypeError: select() received an invalid combination of arguments - got (int, Tensor), but expected one of:
 * (int dim, int index)
      didn't match because some of the arguments have invalid types: (int, !Tensor!)
 * (name dim, int index)
      didn't match because some of the arguments have invalid types: (!int!, !Tensor!)


In [87]:
index_x = torch.tensor([0, 3, 6])
print(index_x.shape)
index_x = index_x.expand(3, 3)
print(index_x.shape)
index_x = index_x.expand(2, 3, 3)

torch.Size([3])
torch.Size([3, 3])


In [88]:
index_x

tensor([[[0, 3, 6],
         [0, 3, 6],
         [0, 3, 6]],

        [[0, 3, 6],
         [0, 3, 6],
         [0, 3, 6]]])

In [71]:
manual_test[0].gather(0, torch.tensor([[0, 3, 6]]))

tensor([[ 0, 13, 26]])

In [74]:
manual_test[0][3,1]

tensor(13)

In [54]:
test_out_ts[0,:,:]

tensor([[ 1,  2,  3],
        [ 1,  2,  3],
        [ 1,  2,  3],
        [ 1,  2,  3],
        [ 1,  2,  3],
        [ 1,  2,  3],
        [ 1,  2,  3],
        [ 1,  2,  3],
        [ 1,  2,  3],
        [ 1,  2,  3],
        [ 1,  2,  3],
        [ 1,  2,  3],
        [ 1,  2,  3],
        [ 1,  2,  3],
        [ 1,  2,  3],
        [ 1,  2,  3],
        [ 1,  2,  3],
        [ 1,  2,  3],
        [11, 12, 13],
        [11, 12, 13],
        [11, 12, 13],
        [11, 12, 13],
        [11, 12, 13],
        [11, 12, 13],
        [11, 12, 13],
        [11, 12, 13],
        [11, 12, 13],
        [11, 12, 13],
        [11, 12, 13],
        [11, 12, 13],
        [11, 12, 13],
        [11, 12, 13],
        [11, 12, 13],
        [11, 12, 13],
        [11, 12, 13],
        [11, 12, 13],
        [21, 22, 23],
        [21, 22, 23],
        [21, 22, 23],
        [21, 22, 23],
        [21, 22, 23],
        [21, 22, 23],
        [21, 22, 23],
        [21, 22, 23],
        [21, 22, 23],
        [2

In [52]:
test_out_ts[:, torch.arange(1, 54, 3), :]

tensor([[[ 1,  2,  3],
         [ 1,  2,  3],
         [ 1,  2,  3],
         [ 1,  2,  3],
         [ 1,  2,  3],
         [ 1,  2,  3],
         [11, 12, 13],
         [11, 12, 13],
         [11, 12, 13],
         [11, 12, 13],
         [11, 12, 13],
         [11, 12, 13],
         [21, 22, 23],
         [21, 22, 23],
         [21, 22, 23],
         [21, 22, 23],
         [21, 22, 23],
         [21, 22, 23]],

        [[ 1,  2,  3],
         [ 1,  2,  3],
         [ 1,  2,  3],
         [ 1,  2,  3],
         [ 1,  2,  3],
         [ 1,  2,  3],
         [11, 12, 13],
         [11, 12, 13],
         [11, 12, 13],
         [11, 12, 13],
         [11, 12, 13],
         [11, 12, 13],
         [21, 22, 23],
         [21, 22, 23],
         [21, 22, 23],
         [21, 22, 23],
         [21, 22, 23],
         [21, 22, 23]],

        [[ 1,  2,  3],
         [ 1,  2,  3],
         [ 1,  2,  3],
         [ 1,  2,  3],
         [ 1,  2,  3],
         [ 1,  2,  3],
         [11, 12, 13],
       

In [50]:
test_out_ts.gather(dim=1, index=torch.arange(1, 54, 3).view(18,1,1))

RuntimeError: Size does not match at dimension 0 expected index [18, 1, 1] to be smaller than self [4, 54, 3] apart from dimension 1

In [49]:
torch.arange(1, 54, 3).shape

torch.Size([18])